import Foundation

/// Common Apple Developer Frameworks
public enum Framework: String, CaseIterable, Sendable {
    case root = "documentation"
    case foundation = "foundation"
    case swiftUI = "swiftui"
    case swift = "swift"
    case uiKit = "uikit"
    case widgetKit = "widgetkit"
    case coreData = "coredata"
    case swiftData = "swiftdata"
    case combine = "combine"
    case watchKit = "watchkit"
    case tvKit = "tvuikit"
    case appKit = "appkit"
    case pencilKit = "pencilkit"
    case avKit = "avkit"
    case avFoundation = "avfoundation"
    case metal = "metal"
    case metalKit = "metalkit"
    case metalFX = "metalfx"
    case photos = "photos"
    case photosUI = "photosui"
    case photokit = "photokit"
    case replayKit = "replaykit"
    case coreHaptics = "corehaptics"
    case accelerate = "accelerate"
    case coreML = "coreml"
    case vision = "vision"
    case visionKit = "visionkit"
    case naturalLanguage = "naturallanguage"
    case speech = "speech"
    case soundAnalysis = "soundanalysis"
    case translation = "translation"
    case arKit = "arkit"
    case realityKit = "realitykit"
    case mapKit = "mapkit"
    case coreLocation = "corelocation"
    case coreMotion = "coremotion"
    case sceneKit = "scenekit"
    case spriteKit = "spritekit"
    case storeKit = "storekit"
    case healthKit = "healthkit"
    case homeKit = "homekit"
    case matter = "matter"
    case passKit = "passkit"
    case webKit = "webkit"
    case callKit = "callkit"
    case network = "network"

    public var jsonURL: URL? {
        Endpoints.topicJSONURL(path: self.rawValue)
    }
}
